// server/config/classicBoardConfig.ts
import { CellData } from './boardConfig';

export const CLASSIC_BOARD_CONFIG: CellData[] = [
  { position: 0, name: "GO", type: "SPECIAL" },
  { position: 1, name: "Old Kent Road", type: "PROPERTY", price: 60, baseRent: 2, group: "a" },
  { position: 2, name: "Community Chest", type: "CHEST" },
  { position: 3, name: "Whitechapel Road", type: "PROPERTY", price: 60, baseRent: 4, group: "a" },
  { position: 4, name: "Income Tax", type: "TAX", baseRent: 200 },
  { position: 5, name: "Kings Cross Station", type: "STATION", price: 200, baseRent: 25, group: "station" },
  { position: 6, name: "The Angel, Islington", type: "PROPERTY", price: 100, baseRent: 6, group: "b" },
  { position: 7, name: "Chance", type: "CHANCE" },
  { position: 8, name: "Euston Road", type: "PROPERTY", price: 100, baseRent: 6, group: "b" },
  { position: 9, name: "Pentonville Road", type: "PROPERTY", price: 120, baseRent: 8, group: "b" },
  { position: 10, name: "Jail / Just Visiting", type: "SPECIAL" },
  { position: 11, name: "Pall Mall", type: "PROPERTY", price: 140, baseRent: 10, group: "c" },
  { position: 12, name: "Electric Company", type: "UTILITY", price: 150, group: "utility" },
  { position: 13, name: "Whitehall", type: "PROPERTY", price: 140, baseRent: 10, group: "c" },
  { position: 14, name: "Northumberland Avenue", type: "PROPERTY", price: 160, baseRent: 12, group: "c" },
  { position: 15, name: "Marylebone Station", type: "STATION", price: 200, baseRent: 25, group: "station" },
  { position: 16, name: "Bow Street", type: "PROPERTY", price: 180, baseRent: 14, group: "d" },
  { position: 17, name: "Community Chest", type: "CHEST" },
  { position: 18, name: "Marlborough Street", type: "PROPERTY", price: 180, baseRent: 14, group: "d" },
  { position: 19, name: "Vine Street", type: "PROPERTY", price: 200, baseRent: 16, group: "d" },
  { position: 20, name: "Free Parking", type: "SPECIAL" },
  { position: 21, name: "Strand", type: "PROPERTY", price: 220, baseRent: 18, group: "e" },
  { position: 22, name: "Chance", type: "CHANCE" },
  { position: 23, name: "Fleet Street", type: "PROPERTY", price: 220, baseRent: 18, group: "e" },
  { position: 24, name: "Trafalgar Square", type: "PROPERTY", price: 240, baseRent: 20, group: "e" },
  { position: 25, name: "Fenchurch Street Station", type: "STATION", price: 200, baseRent: 25, group: "station" },
  { position: 26, name: "Leicester Square", type: "PROPERTY", price: 260, baseRent: 22, group: "f" },
  { position: 27, name: "Coventry Street", type: "PROPERTY", price: 260, baseRent: 22, group: "f" },
  { position: 28, name: "Water Works", type: "UTILITY", price: 150, group: "utility" },
  { position: 29, name: "Piccadilly", type: "PROPERTY", price: 280, baseRent: 24, group: "f" },
  { position: 30, name: "Go To Jail", type: "SPECIAL" },
  { position: 31, name: "Regent Street", type: "PROPERTY", price: 300, baseRent: 26, group: "g" },
  { position: 32, name: "Oxford Street", type: "PROPERTY", price: 300, baseRent: 26, group: "g" },
  { position: 33, name: "Community Chest", type: "CHEST" },
  { position: 34, name: "Bond Street", type: "PROPERTY", price: 320, baseRent: 28, group: "g" },
  { position: 35, name: "Liverpool Street Station", type: "STATION", price: 200, baseRent: 25, group: "station" },
  { position: 36, name: "Chance", type: "CHANCE" },
  { position: 37, name: "Park Lane", type: "PROPERTY", price: 350, baseRent: 35, group: "h" },
  { position: 38, name: "Super Tax", type: "TAX", baseRent: 100 },
  { position: 39, name: "Mayfair", type: "PROPERTY", price: 400, baseRent: 50, group: "h" },
];